### ISSUE TITLE
Question regarding update to Castle 3.0 and nuget package

### ISSUE THREAD

**Issue by Cyber1000** [davybrion/Agatha#24]
Hi, thanks for this great piece of work!

I've updated the sources of Agatha to Castle 3.0, because there where problems with the Castle 3.0 (actually the restrictions in Container.ComponentRegistration changed a little bit). It seems to work without problems, at least in my projects.
So for now:
- Silverlight-Components are missing, cause I haven't installed it right now.
- I couldn't test it thoroughly, cause I don't have xUnit installed, but so far I have no problems.

Questions:
- Should I test silverlight and xUnit or may someone other look over this? (I could even make the changes for silverlight, even if I can't open these projects in visual studio, they should be similar to my other changes)
- I have now Castle.Windsor.3.0.0.4001 and Castle.Core.3.0.0.4001 in my packages-folder (besides Castle.Core.2.5.2 and Castle.Windsor.2.5.3). Should I just delete the old packages (cause they are not used any more after my changes) and checkin the new packages? At work we have packagerestore enabled, but agatha seems to have nuget-packages checked in.
- Are there any plans to update nuget.packages to 1.4? (or to 1.3.1, if we aren't this far). Perhaps other IoC should be updated as well?

Thanks,
Harald

**Comment by davybrion** [comment]
i'll try to upgrade the silverlight stuff if you send a pull request

the old windsor packages need to be removed from the packages folder, but leave them in for now until the silverlight projects are updated

and yeah, we should probably upgrade all IoC container packages to their latest versions

**Comment by davybrion** [comment]
1.3.1 depends on Castle Windsor 3.0
