### ISSUE TITLE
Decouple "logging" from Agatha

### ISSUE THREAD

**Issue by mwpowellhtx** [davybrion/Agatha#36]
Hello,

I'm not sure what [issue 22](https://github.com/davybrion/Agatha/issues/22) is, but I'd like to encourage the Agatha team to strongly consider abstracting away through some sort of adapter layer the logging concern(s).

I am finding that these dependencies are killing the forward momentum in one of my projects and being able to choose whether I want Common.Logging, log4net, or something completely different, or nothing at all, would be great.

Thank you...

**Comment by michaelaird** [comment]
I believe @davybrion has declared this project "done". I think it's up to you to fork it and make whatever changes you need...
