### ISSUE TITLE
Using latest version of Castle.Windsor 2.5.3 (with Castle.Core 2.5.2)

### ISSUE THREAD

**Issue by moodmosaic** [davybrion/Agatha#5]
Are there any plans to use Castle.Windsor 2.5.3 and Castle.Core 2.5.2 in Agatha Castle adapter? In my local clone all tests passed. (Or we wait for Castle.Windsor 3.x which is going to be released soon?)

**Comment by davybrion** [comment]
there were no plans to upgrade, but that's only because i wasn't keeping up with the various container releases :)

there's no need to wait for 3.x as far as i'm concerned

**Comment by moodmosaic** [comment]
Yes, it's quite hard to keep up with all those containers. I would upgrade every 6-7 months though, just to keep up with the major changes. I'm using Windsor and after 2.5 release, it requires just two assemblies to run (as opposed to four previously). Many users might need to recompile the whole Agatha.Castle adapter just for this. (I may send a pull request with the updated assemblies, it will be fine either it gets merged or not)

**Comment by davybrion** [comment]
i'll definitely merge it, no worries :)

the agatha sources are downloaded more than the binary package which indeed suggest that many people rebuild against the specific container version they use

**Comment by moodmosaic** [comment]
yes, that was the first thing I also did :) but I'm always afraid, you know, if newer versions of containers have slightly different behaviour (and I always hope that it will show up on the unit-tests!)
